server_url: ${SERVER_URL}
speed: 3
user_login: ${USER_LOGIN}
user_password: ${USER_PASSWORD}
headless: ${HEADLESS}
log_level: INFO
strategy: balanced_economic_growth
minimum_storage_capacity_in_hours: 2
hero:
  adventures:
    minimal-health: 50
    increase-difficulty: true
  resources:
    support-villages: true
    attributes-ratio:
      fighting-strength: 25
      production-points: 75
